---

#EXPLANATION ON HOW TO PLAY THIS PLAYBOOK.
# 1. My objectif was to put everything in one playbook. And so to be able to only execute _certain_ tasks of the playbook but not everything, I used tags
# 2. As you can see below, some individual tasks have tags. You can add them, alter them easily. See the playbook, the tags are under 'name'.

#Execute a task:
#If you want to only execute the task for installing webserver then you use this command:
#COMMAND:  ansible-playbook --tags web function.yml
#Why ? Well, because there is the tag web to 'install webserver' task. There is also apache2 tag. Choose which tag you want to use, it doesn't matter

#To see lists of tags: 
#COMMAND: --ansible-playbook --list-tags function.yml

#I hope it helped ! PS: Issam :))

#basic tag: nmap, vim.





########### Only leerlingen devices
- hosts: leerlingen
  tasks:
   
#1. Update
  - name: install updates (Debian)
   #tags 'always' here under. Will always be executed
    tags: always
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Debian" 
    #when ansible is Debian -> 
    # not necessary. But I added it for security measures. If one day a non debian device makes a connection (will not happen normally because inventory is manually config)

#2. Install Apache
  - name: install webserver (Debian) 
    #You can choose to write web or apache2 in tags, it doesn't matter. If you choose 1 of the 2 it will execute that here.
    tags: web,apache2
    apt:
      name:
        - apache2
    when: ansible_distribution == "Debian"


#3. Remove Apache
  - name: remove webserver (Debian)
    tags: delweb,delapache2
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Debian"

#4. Download a few basics packages
  - name: install basic (nmap - vim - wireshark)
    tags: basics
    apt:
      name:
        - nmap
        - vim
        - wireshark
      state: latest
    when: ansible_distribution == "Debian"


############## Install Packet Tracers commandos
- name: Install Packet Tracer
  hosts: leerlingen
  tasks:

#To only download it once
  - name: Check if Packet Tracer is installed
    tags: ptracer
    stat:
      path: /var/flag/packettracer_installed.flag
    register: packettracer_installed
  
  
#1. Broken packages
  - name: install broken packages (necessary for packet tracer)
    tags: ptracer
    command: apt --fix-broken install


#2. Dialog ( for packet tracer)
  - name: install dialog
    tags: ptracer
    apt:
      name: dialog
      state: present


#3. Download Packet Tracer on all hosts
#  - name: Download Packet Tracer installer
#    tags: install2
#    when: packettracer_installed.stat.exists == false
#    get_url:
#      url: "https://archive.org/download/cisco-packet-tracer-821-ubuntu-64bit/CiscoPacketTracer_821_Ubuntu_64bit.deb"
#      dest: /tmp/packettracer_821_installer.deb
#      remote_src: yes


#3.5 Download Packet Tracer on all hosts but with 'Copy'
#After testing I noticed it's _waaaay_ faster this way. Always possible to use above if you prefer.  
  - name: Download Packet Tracer installer
    tags: ptracer, install
    when: packettracer_installed.stat.exists == false
    copy: 
      src: ~/ansible_desktop/software/packettracer_821_installer.deb
      dest: /tmp/packettracer_821_installer.deb


#4. Debconf - Non interactive mode
  - name: Non Interactive, No more asking to accept EULA terms
    tags: ptracer,debconf
    command: echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

#5. Auto-Accept ELUA - Downloading ...
  - name: Accept EULA - Downloading ...
    tags: ptracer,launch
    when: packettracer_installed.stat.exists == false
    async: 300
    poll: 10
    command: dpkg -i /tmp/packettracer_821_installer.deb
    register: packettracer_install_result

#6 Create flag directory to store file
  - name: Create flag directory
    tags: ptracer
    file:
      path: /var/flag
      state: directory

#7. Create the flag file to indicate packet tracer is installed on that specific device
  - name: Flag indicating ptracer installed
    tags: ptracer 
    when: packettracer_install_result is succeeded
    file:
      path: /var/flag/packettracer_install.flag
      state: touch


  
